---
title: "ESS Voting Anlysis"
subtitle: "Testing differnt causal paths..."
author: "Rebecca & Simon "
#output: html_notebook
output: github_document
---

# Start

Hi, this is Becci's and Simon`s working page for writing the last semester paper on democratic participation. The main purpose is to perform different statistical methods in order to gain insights to the populist voting profiles. The broader question that drives this analysis is **who is attracted to give her/his vote to a populist and especially a right-wing party?** Different causal paths will be proposed and rigorously be tested by evidence from ESS and CHES data. Another aspect will be visualizing country-wise effects and model performance to get a better understanding of a model's fitting to the national context. 


## ToDo

* Why not use interaction variable of vote_right and protest as y?
* Is there a reasonable party_id/ voting_id coverage?
* Derive final research question
* fitting models
* write semester paper:
    + Die Studierenden führen für 12 LP abschließend eine eigene Untersuchung durch zu **zwei oder mehr selbst gewählten Beteiligungs- bzw. Entscheidungsprozessen**, um eine konkrete Forschungsfrage zu beantworten (ca. 30 Seiten). Wieviele Seiten zu Zweit?
* http://students.brown.edu/seeing-theory/basic-probability/index.html#section2

## Research Question(s)

* internal and external political efficacy  -> likelihood to vote right/populist or green party? Cultural clash. 
* Are citizens who live in systems that provide extensive direct democratic decision-making processes characterized by higher levels of trust in political institutions and higher external political efficacy?
* ESS in combination with direct democracy dataset?
* Macro predictors: political system or number of referendum
* Multilevel-Bayesian Regression. 


## EDA

* Check selective or pairwise compare correlations (stepwiseAIC or multilevel prediction tree).
* spatial mapping
* Factor scores (Factor Analysis)
    + Trust (target)
    + Imm (X)
    

## Statistical Modeling

### Multilevel 

* Y = voting right wing/populist
* X_1 = ex_eff (trust factor scores) + in_eff
* X_2 = immigration(factor scores)
* X_3 = s_gov + s_dem + interaction + demo + sign_pet
* X_4 = poli_intr + lrscale + party_act + news_pol
* X_5 = gndr + edu + income + rel + year
* X_6 = social_lazy (social benefit attitudes)
* What about Z predictors?


### Prection Power

* multilevel tree
* `brms`
* viele random slopes
