---
title: "ESS Statistical Models"
subtitle: "Factor Scores"
author: "Rebecca & Simon "
output: html_notebook
---

## Packages

```{r}
pacman::p_load(dplyr, ggplot2, readr, haven, purrr, magrittr, labelled, sjPlot, viridis, forcats, ggthemes, tidyr, broom)
# devtools::install_github("tidyverse/tidyr")
```

## Load Data

```{r}
options(scipen = 999)
ess <- get(load("data/Rdata/ess_scores.Rdata")) %>%
  mutate(
    id = 1:n(),
    round_year = case_when(
      round == 8 ~ "2016",
      round == 7 ~ "2014",
      round == 6 ~ "2012",
      round == 5 ~ "2010",
      round == 4 ~ "2008",
      round == 3 ~ "2006",
      round == 2 ~ "2004",
      round == 1 ~ "2002",
      TRUE ~ "") %>% 
      as.numeric
    )
ches <- get(load("data/Rdata/ches_clust.Rdata")) %>%
  select(party_id, vote_id, cluster, lrgen)

vdem <- get(load("data/Rdata/vdem.Rdata"))
vdem$pol_kill <- NULL

vdem <- vdem %>%
  select(country, year, reason, common, counter_arg, elite_consul, engage_soc, clientelistic, welfare_working, equal_edu, equal_health) %>%
  mutate(country = as.character(country))
```


## Merge Data

```{r}
sel <- ess %>%
  group_by(country, round_year) %>%
  tally

vdem_list <- list()
for(jj in seq_along(sel$country)){
  temp <- vdem %>%
    filter(country == sel$country[1]) %>%
    filter(year %in% (sel$round_year[1]-2):(sel$round_year[1]+2))
  
    if(nrow(temp) == 0){
      temp <- vdem %>%
        filter(country == sel$country[jj]) %>%
        arrange(desc(year)) %>%
        slice(1:3)
    }

  vdem_list[[jj]] <- temp
}

vdem_window <- bind_rows(vdem_list) %>%
  group_by(country) %>%
  summarise_if(is.double, mean, na.rm = T) %>%
  ungroup()

dat <- ess %>% 
  left_join(ches, by = c("vote_id", "party_id")) %>%
  left_join(vdem_window, by = c("country")) %>%
  mutate(vote_right = ifelse(cluster == "Right Populist", 1, 0)) %>%
  mutate(lr_dff = abs(lrscale - lrgen))

glimpse(dat)
#save(dat, file = "data/Rdata/data_final.Rdata")
```



```{r}
dat %>%
  dplyr::select(lr_dff, lrgen, lrscale) %>%
  summary

table(dat$vote_right)
table(dat$cluster)


dat %>%
  filter(!is.na(vote_right)) %>%
  group_by(country, gndr, vote_right) %>%
  tally %>%
  filter(vote_right == 1) %>%
  ggplot(aes(gndr, n, fill = as.factor(gndr))) +
  geom_bar(stat = "identity") +
  facet_wrap(~country, scales = "free") +
  ggthemes::theme_hc() +
  ggthemes::scale_fill_hc()

dat %>% 
  mutate(vote_right = as.factor(vote_right*(gndr))) %>%
  ggplot(aes(vote_right, pc_trust, colour = vote_right)) +
  geom_boxplot()
```


# Modeling


```{r}
#devtools::install_github("lme4/lme4")
library(lme4)
glmer_base <- glmer(vote_right ~ (1|country), data = dat, family = binomial(link = "logit"))

glmer1 <- glmer(vote_right ~ pc_trust + pc_imm + pc_imm_econ + (1|country), data = dat, family = binomial(link = "logit"))
arm::display(glmer1)

glmer2 <- glmer(vote_right ~ pc_trust + pc_imm + pc_imm_econ + gndr + pol_inter + scale(edu) + scale(rel) + (1|country), data = dat, family = binomial(link = "logit"))

glmer3 <- glmer(vote_right ~ pc_trust + pc_imm + pc_imm_econ + gndr + pol_inter + scale(edu) + scale(rel) + engage_soc + elite_consul +(1|country), data = dat, family = binomial(link = "logit"))

glmer4 <- glmer(vote_right ~ engage_soc + elite_consul + (1|country), data = dat, family = binomial(link = "logit"))

library(stargazer)
#stargazer(glmer_base, glmer1, glmer2, glmer3, glmer4, type = "latex")
library(texreg)
screenreg(list(glmer1, glmer2, glmer3, glmer4))
```

## PURRRRRR

```{r}
dat_nest <- dat %>%
  #filter(country %in% c("Germany", "France", "Belgium")) %>%
  drop_na(vote_right, pc_trust) %>% # enferene Zeilen die NA an bei diesen Vars haben. 
  group_by(country) %>% # gruppiere den Datensatz pro Jahr (oder Land oder sonstigem Kontext).
  tidyr::nest() %>% # unspeichere ihn selbst in eine Zelle
  arrange(country) # dann ordne nach Jahr.

dat_nest$data[[1]]
```

* http://www.machinegurning.com/rstats/iterating/

```{r}
fun_fit_logit <- function(df){
  glm(vote_right ~ pc_trust, data = df, family = binomial(link = "logit"))
}
# vote_right ~ pc_trust + pc_imm + pc_imm_econ + gndr + pol_inter + scale(edu) + scale(rel) + (1|country)

library(purrr)
models <- dat_nest %>%
  mutate(mod = data %>% map(fun_fit_logit))

glimpse(models)

library(modelr)
mod <- models %>% 
  dplyr::mutate(
    tidy_glm = mod %>% map(broom::tidy),
    glance_glm = mod %>% map(broom::glance),
    bic_glm = glance_glm %>% map_dbl("BIC"),
    n_glm = data %>% map_int(nrow),
    r2 = mod %>% map_dbl(~rsquare(., data = gapminder)),
    aic = mod %>% map_dbl(fit, ~AIC(.))
    #aug_glm = mod %>% map(broom::augment)
    #res_glm = aug_glm %>% map(".resid") 
  )

glimpse(mod)
mod$glance_glm[[1]]

mod$tidy %>% map(print)

mod %>%
  ggplot(aes(n_glm, bic_glm)) +
  geom_point() +
  geom_smooth(method = "lm")

mod %>%
  ggplot(aes(bic_glm)) +
  geom_histogram()


reg=function(x,y,w=rep(1,length(x))){
  result=lm(y~x,weights=w)
  return(result)
}
myRegs=map2(myX,myY,safely(reg))
map2(myX,myY,safely(reg))

# Create a helper function that returns TRUE if a number is even
is_even <- function(x){
  !as.logical(x %% 2)
}
map_if(numbers, is_even, sqrt)

# trans list
transpose(safe_result_list)
listviewer::jsonedit(length_data)

### goes over errors and does not stop execution
possible_sqrt <- possibly(sqrt, otherwise = NA_real_)
numbers_with_error <- list(1, 2, 3, "spam", 4)
map(numbers_with_error, possible_sqrt)

### capture error in callback
safe_sqrt <- safely(sqrt, otherwise = NA_real_)
map(numbers_with_error, safe_sqrt)


# Function to select columns in the raw data
filterColumns <- function(x,y){
    x[,(colnames(x) %in% eval(parse(text=y)))]
}

# Create X and Y columns
starter_df %<>% 
  transmute(
  id,
  pred_varsets,
  train.X = map2(rawdata, pred_varsets,  ~ filterColumns(.x, .y)),
  train.Y = map(rawdata, ~ .x$medv)
  )

m1 <- 'lifeexp ~ pop + gdppercap'
m2 <- 'lifeexp ~ pop + gdppercap + continent + year'
m3 <- 'lifeexp ~ pop + gdppercap + country + year'
m4 <- 'lifeexp ~ pop + gdppercap + year*country'

model_frame <- data_frame(model = c(m1, m2, m3,m4)) %>%
mutate(model = map(model, as.formula))

model_frame <- data_frame(model_name = c("simple", "medium", "more", "woah"), model = list("simple" = m1, "medium" = m2, "more" = m3, "woah" = m4)) %>%
  mutate(model = map(model, as.formula))

model_frame

# Huh well that worked, but something is weird. Our nice gapminder dataframe is now a list. How can we do this and keep things as a dataframe? We can use the purrrlyr package to do this, which has handy parallels of the functions in purrr, but designed to deal with and give back dataframes.

gapminder %>%
purrrlyr::dmap_if(is.factor, as.character) %>% 
  head()
```



## EDA 

```{r}
dat %>%
  mutate(g = as.factor(vote_right)) %>%
  ggplot(aes(g, pc_trust, colour = g)) +
  geom_boxplot()
```

```{r}
dat %>%
  mutate(g = as.factor(vote_right)) %>%
  ggplot(aes(g, pc_imm, colour = g)) +
  geom_boxplot()

nn <- dat %>%
  filter(!is.na(vote_right)) %>%
  mutate(vote_right = as.numeric(vote_right)) %>%
  ggplot(aes(pc_imm, vote_right)) +
  #geom_rug(aes(colour = as.factor(vote_right)), sides = "tb") +
  geom_jitter(aes(colour = as.factor(vote_right)), alpha = .1) +
  #geom_density(aes(colour = as.factor(vote_right))) +
  #stat_smooth(method="glm", family="binomial", formula=y~x, alpha=0.2, size=2)
  geom_line(
    data = data.frame(
      pc_imm = seq(-3,3,0.1),
      vote_right = predict(glm(vote_right ~ pc_imm, family = "binomial", data = dat),
        newdata = data.frame(pc_imm = seq(-3,3,0.1)), type = "response")
      )
    )
nn  
#geom_smooth(method = "glm", color = "black", family = "binomial") 
```

```{r}
dat %>%
  filter(!is.na(vote_right)) %>%
  mutate(g = as.factor(vote_right)) %>%
  ggplot(aes(g, fill = as.factor(gndr))) +
  geom_bar(position = position_dodge())
```


```{r}
dat %>%
  mutate(g = as.factor(vote_right)) %>%
  ggplot(aes(g, pc_imm_econ, colour = g)) +
  geom_boxplot()
```





```{r}
glimpse(dat)

#devtools::install_github("strengejacke/sjPlot")

library(sjPlot)
#data_final$trust_scores
ml1 <- glmer(vote_right ~ pc_trust + pc_imm + pc_imm_econ + gndr + scale(edu) + scale(rel) + (1|country), data = dat, family = binomial(link = "logit"))
arm::display(ml1)
sjp.glmer(ml1)
# fixed params
plot_model(ml1, type = "est")
# plot_model(ml1, type = "std2")
ggran <- plot_model(ml1, type = "re", sort.est = T)

predict(ml1)


library(forecast)
ggran$data %>%
  mutate(term = fct_reorder(term, estimate)) %>%
  ggplot(aes(term, estimate)) +
  geom_point() + 
  coord_flip()

# random params
# marginal effects
sjp.glmer(ml1, type = "eff", vars = "rel")
sjp.glmer(ml1, type = "eff", vars = "gndr")
sjp.glmer(ml1, type = "eff", vars = "pc_trust")
sjp.glmer(ml1, type = "eff", vars = "pc_imm")
sjp.glmer(ml1, type = "eff", vars = "pc_imm_econ")
```

```{r}
sjp.glmer()
```




## brms

```{r}
library(brms)
fit <- brm(vote_right ~ trust_scores + (1|country), data = data_final, family = binomial("probit"))
summary(fit, waic = TRUE) 
plot(fit)
```






```{r}
summary(data_final)
glm2 <- glmer(vote_right ~ trust_scores + gndr + rel +(1|country), data = data_final, family = binomial(link = "logit"))
display(glm2)

library(sjPlot)
ggg <- sjp.glmer(glm2, type = "eff")
ggg
```

```{r}
ml1 <- lmer(lr_dff ~ trust_scores + gndr + (1|country), data = data_final)
display(ml1)
```


```{r}
library(sjPlot)
plot_model(ml1)
```




