---
output: pdf_document
---
In the 2009 European Parliamentary elections, especially right-wing parties mobilized anti-EU sentiment and gained seats in the European parliament.

 Since the early 1980s, parties such as the
French Front National, the Belgian Vlaams Blok, the Austrian Freedom Party
(FPÖ) and the Danish People’s Party have established themselves in their
respective party systems, sometimes with vote shares exceeding 20 per cent.

In the following study we are eager to answer the question whether ...

In this article, we will try to explain differences in extreme right-wing voting behaviour between 16 Western European countries. So far, cross-national empirical research on extreme right-wing voting has been scarce, even though in 1988 von Beyme emphasized that ‘future studies of right-wing extremism will have to pay more attention to the whole political context of the political movement’ (von Beyme 1988: 16).


[@buhl06]: 
Since Lazarsfeld et al. (1949), socio-economic status (SES) has played a prominent role in explaining both the decision to vote and participation behaviour. Normally, socio-economic status consists of the individual’s educational level, income, and her occupational status. In theory, a high SES leads to a higher propensity to participate in elections, because individuals with high education levels and/or with a high income have more disposable time and a greater capacity to understand political debates (Kleinhenz 1995). This leads not only to greater political interest, but also to a greater probability of participation. Furthermore, wealthy individuals have an interest in contributing to the stability of the political system by participating in it (Wol nger and Rosenstone 1980).
• Political skills are seen as the most important resource of participation (Bühlmann 2006): individuals with a lot of political interest (Campbell et al. 1976; Lazarsfeld et al. 1949) and internal ef cacy (Campbell et al. 1976) make wider use of all the different possibilities of in uencing politics - including electoral participation - than uninterested individuals or persons who do not think they have the ability to participate in politics.2
• Political attitudes play a crucial role in the decision to vote. Since Campbell et al. (1976), party ties have been considered long-term factors which stabilise electoral choices. However, party ties are also important for participation (Dalton et al. 1984). People with only weak, or no party identi cation at all, show a lower propensity to participate in elections (Pattie and Johnston 1998). An important and widely discussed (especially in German political science (Feist 1992))3 factor is the attitude that voting is a civic duty. If participation in elections is seen as the ful lment of one’s duty as a citizen, the propensity to vote increases.

@kenski2006connections: 
Research in several European countries has shown that voters for the radical
right-wing parties feel less politically efficacious, more alienated, and more dissatisfied with the established parties, the political institutions, and the demo..
cratic system in general (Beta 1994:35..67).



@buhlmann06 : 
Any attempt to explain an individual’s propensity to vote must take into account the differences in the context in which the individual lives. We mainly assume that different contextual settings will have different impacts on individual participation. We also expect different interactions between contextual and individual characteristics. In other words: differences in individual resources play a key role in explaining individual participation behaviour, but the latter also depends on the canton in which a person lives. On the one hand the cantonal context builds a framework which fosters or hinders the individual’s propensity to vote, and on the other hand, the effect of individual resources on participation also differs from context to context.

Third, we advance a methodological argument. We hypothesise that an individual’s propensity to vote is in uenced by both his personal characteristics as well as by contextual attributes. Individual-level explanations of electoral participation on the one hand typically argue that non-voting is determined by a combination of facilitative and motivational variables. Motivational factors as such include ideology, political attitudes, and basic tendencies, whereas facilitative determinants refer to speci c individual resources and socio-demographic factors (education, income, age etc.) (Kleinhenz 1995; Knight and Marsh 2002). Macro-level approaches, on the other hand, evaluate the determinants of total voting turnout rather than focusing on the individual (Franklin 2002; Norris 2002). In this strand of research, cross-country variance is explained by cultural, economic, and – most importantly – politico-institutional settings (Blais and Dobrzynska 1998; Crepaz 1990; Franklin 2002; Freitag 1996, 2005; Norris 2004; Wernli 1998). While micro-level research neglects the contextual framework within which individual actions take place, macro-level approaches face the risk of ecological fallacies. Against this background, we argue that non-voting has to be explained by both individual and contextual characteristics. Moreover, the environmental context also functions in an interactive manner, in uencing the strength of the effect of individual characteristics on participation.
By combining individual and contextual determinants of electoral participation and modelling them simultaneously with multilevel analysis, we contribute to the overcoming of the “midlife crisis” facing electoral studies (Curtice 2002: 6). We see multilevel analysis as a possibility to overcome the micro-macro dualism widely discussed in social sciences. With multilevel analyses, the determinants of individual behaviour can be analysed in a much more appropriate manner than with simple micro-analyses or macro-analyses (Hank 2003).
For the  rst time, data on the 2003 Swiss elections allows the in uence of the cantonal contexts on individual participation to be tested. We can therefore go further than the very rare existing studies on electoral participation in Switzerland, which are conducted either on the aggregate (Freitag 2005; Wernli 1998, 2001) or the individual level (Ballmer-Cao and Sgier 1998; Bühlmann et al. 2003).
This contribution is divided into four sections. Before we turn to a short description of our method and our results we discuss the existing theoretical and empirical contributions to our investigation (next section). Our last section offers conclusions and outlines for future research.







So far, these factors have been studied in isolation and have not as yet been integrated into an explanatory model of cross-national differences in extreme right-wing voting. This article is among the first to take all these factors into account for all countries of the European Union and Norway using a multi- level approach. This approach also allows us to examine how the contextual and individual levels are interrelated. It brings together a large amount of individual-level survey data (N = 49,801). Moreover, country characteristics are added from census data as well as data from an expert judgement survey conducted among political scientists in all countries included in the study to trigger information on the opportunity structure for extreme right-wing parties as well as their specific characteristics (Lubbers 2000). To summarize, we answer the question as to what extent differences between countries in extreme right-wing voting can be explained in terms of (a) composition effects, (b) country conditions, and (c) characteristics of extreme right-wing parties themselves. Moreover we examine how individual-level effects differ between countries and to what extent these differences are influenced by contextual conditions.



Whether or not this fear is justified, the fact remains that many countries have witnessed a growing popularity of these parties since the 1980s and that this growth in popularity is mirrored by a declining popularity of the more traditional political parties.



he ability of populist politics to galvanize new forms of political engagement is especially important in an era of decline in formal political participation such as turnout and party membership @skocpol2016tea. At the same time, in unconsolidated democracies populism may erode democratic institutions and usher competitive authoritarian regimes [@levistky2012populism].

populist politics can reshape repertoires of political mobilization, especially in the forms of mass social movements and socially engaged party organizations [@hawkins2010venezuela; @jansen2011populist].
