---
output: pdf_document
---

These past years populism has received great attention from the social science community [@mudde2004populist; @mudde2017populism]. The term ‘populism’  is both widely used and disputed [@roberts2006populism; @barr2009populists]. Several scientists have taken on the challenge of conceptualising populism with only a small number of widely acknowledged characteristics. It has been considered as an political style, as an ideology and as an organizational form [@pauwels2014populism]. Often, the concept is broken down to political, economic, social, cultural and discursive features and analyzed from numerous theoretical perspectives including democratic and modernization theory, social movement theory, party politics and political psychology [@postel2007populist; @goodliffe2012resurgence; @acemoglu2013political]. Within the wide range of literature there is a general agreement that populism is context-dependent and culture-bound, therefore strongly variable across countries. By the means of cross-national analyses, @mudde2012populism were able to gain extensive insight into populism and democracy in Latin America, Canada, Eastern and Western Europe. 

Further scholars differentiate populism based on historical periods with studies using data going back to the late 19th century [@arter2010breakthrough; @rosenthal2012steep; @levitsky2013resurgence]. Furthermore, populism cuts across ideological cleavages [@kaltwasser2014responses]: in Europe, an exclusionary right-wing variant of populism emerged in the 1980s—and has intensified since—targeting mostly immigrants and national minorities [@mudde2007populist; @ivarsflaten2008unites; @art2011inside; @berezin2013normalization]. Finding common traits which combine various populist activites across several countries remains a great challenge. The task therefore is to explain how specific circumstances and culture nature populists politics and how these in turn impact the political sphere [@arter2010breakthrough]. Despite such difficulties, it is possible to conceptualise populism by clearly identifing the key features of the phenomenon to be observed, allowing a comparison of populist politics across contexts. 

The increase of right-wing extremism is of great matter in several Western European democracies. While right-wing parties with conservative and anti-system attitudes are gaining more and more ground in the political arena, the actual democratic process is jeopardised [@coffe2007fertile].
Comparative evidence on the intentions of right-wing voters is rather insufficient [@kai2008protest]. Several analyses have shown that vote intentions and therefore election outcomes for right-wing parties are affected by political, economic and social circumstances such as the political landscape, socio-econonmic characteristics, political trust, the presence of immigrants, crime rate and social capital [@carter2002proportional; @golder2003explaining; @coffe2007fertile]. 

Most comparative analyses either observed solely on the individual level or on the aggregate level. In aggregate-level studies, several country-specific characteristics connected to the vote of right-wing parties were identified [@lubbers2002extreme]. However, when analysing the context, individual characteristics on voting for the right wing are often disregarded [@merkl2014revival]. Further researchers recognized these flaws and derived important factors to explain variations between several countries [@husbands1996racism; @van2000anti]. @lubbers2002extreme propose the distinction between political, economic and sociological factors. While the party system and party-specific factors play an important part from the political perspective, economic competetion and malaise as well as immigrants have to be considered when explaining differences in right-wing voting [@husbands1996racism; @lubbers2002extreme]. @werts2013euro found evidence for the impact of increasing immigration rates as well as the use of such by right-wing parties in order to mobilize their voters [@werts2013euro]. Sociological factors however refer to the social structure and the public opinion within it and are often tested with data on education and attitudes towards ethnic minorities. 

Recent findings from France and Denmark however show that economic factors are not the prevalent explanation, rather cultural ethnic threats and their effect on far-right support [@ivarsflaten2005vulnerable]. Findings by @lubbers2007voting support the idea of important differences between cultural and economic threats in order to explain right-wing voting. @werts2013euro derive from the national identity approach "[...] that the EU poses same threat as mass migration, i.e. a threat to a supposed homogeneous society" [@werts2013euro, p. 188]. Turning to the EUs institutions, @werts2013euro find political distrust being a relatively important attitude of right-wing voters. @ivarsflaten2005vulnerable showed that euro-scepticism is an important determinant for radical right-wing support in France and Denmark. @van2005some also found a positive relationship between anti-EU sentiments and radical right-wing voting in France. Citizens who perceive deprivation in their current situation, have higher levels of political distrust and therefore are more inclined to vote for a right-wing party. 
Also, @arzheimer2009christian found evidence for the relevance of euro-scepticism, although he was not able to test its effect next to the major predictors such as attitudes towards migrants.

Next to the presence of a variety of material resources, political participation is also triggered by cognitive resources such as political trust and efficacy. 

zu trust:

Past research has not highlighted the role of political trust. Especially evidence on the relationship between trust and voting for right-wing parties is not suffiecient, as its impact might have been overestimatedpast methodological approaches might have overestimated its impact. 
Additionally, previous studies did not pay the sufficient attention to the role of political trust, and they found contradictory results (Bergh, 2004; Norris, 2005). They also overlooked the fact that the impact of trust might depend on the characteristics of the context. Moreover, the relationship between trust and vote has not been sufficiently controlled by other explanatory factors, which may have overestimated the impact of trust.




Over the last 40 years, internal efficacy almost always occurs when explaining political participation. Within this literature, internal efficacy is predominantly characterized as a stable psychological resource used to overcome the costs of participation [@valentino2009efficacy]. Political deliberation can also have quite powerful effects on what @morrell2005deliberation calls ‘situation-specific’ internal efficacy: the ability to discuss, understand, and make decisions about politics. It refers to citizens’ feelings of their own personal competence to participate in politics, and scholars have demonstrated that it has important consequences for democracy by influencing citizens’ political participation [@morrell2005deliberation]. While the concept of political efficacy is widely studied, literature and especially empirical evidence of its impact on voting behaviour are rather scarce. In order to overcome these flaws, we analyse several theoretic perspectives which take individual as well as aggregate characteristics into account. By combing these, we hope to develop a more precise concept for cross-country evaluation of right-wing voting. Moreover we are eager to contribute essential evidence to the internal efficacy and political psychology literature. 

