---
output: pdf_document
  fontsize:
---

During the past two decades, the radical right has re-emerged as an electoral force in Western Europe and is changing citizens' political participation. There are many other ways in which citizens can get involved in the political process. Once this is recognized, the challenge is to clarify what we mean by political participation, what activities are and are not covered by the concept. [@brady1995beyond, p. 38] provide the standard definition of political participation. For them, it refers to "activity that has the intent or effect of influencing government action - either directly by affecting the making or implementation of public policy or indirectly by influencing the selection of people who make those policies."[@verba1995voice].

As most modern representative democracies are built upon electoral processes, participation in elections is typically the most common form of citizen political engagement. [@easton1965systems] considers elections an important source of legitimisation. The political system and its representatives obtain the citizens’ support only if the latter are satisfied by the output of the system [@buhl06]. Electoral outcomes determine who manages the affairs of government and who makes public policy. The selection of leaders and the ability to vote someone else at the next election are the publics ultimate instruments of non-violent power. Indeed, the competative nature of electoral politcs encourages elites and citizens to discuss the policies of the government and the bahiour of potential policy-makers [@blais2010political]. From the perspective that voters behave rationally (i.e., goal oriented), thefirst and most obvious motive for electoral choices that can be distinguishedtheoretically is a voter’s wish to affect public policies. To the extent that voterswish to influence policies by means of voting, they tend to vote for the party with which they agree most on issues deemed important. 

Early studies suggest that while most parties are known for their wide-ranging agenda on several political issues, most righ-wing parties were characterised as alliances concerned with one single issue: immigration [@husbands1988dynamics; @eatwell1998dynamics]. However, more recent studies have demonstrated that, even though voters for these parties tend to hold hostile attitudes towards foreigners, broader ideological concerns are more important determinants of right-wing voting [@van2000anti; @husbands2013racial]. It has been shown empirically that positions of voters as well as partieson a variety of different issues are largely structured by left/right ideology [@van2000anti]. Inmost countries the first dimension in particular – left-libertarian versus right-authoritarian – was proven to be strongly correlated with ideological left-rightorientations.


## Individual-level Explanations

### Political Distrust


Populists argue that they despise the political system of representative politics itself [@taggart2000populism]. Moreover, populists are characterised being against the political establishment, the economic, media and cultural elite. Each of them are portrayed as one homogeneous corrupt group acting against the ‘general will’ of citizens [@mudde2017populism]. Therefore populism tends to develop an inner group working against the corrupt others.  As Mudde and Kaltwasser elaborate furthermore, *“This anti-elitist impetus goes together with a critique of institutions such as political parties, big organizations, and bureaucracies, which are accused of distorting the ‘truthful’ links between populist leaders and ‘the common people’”* [@mudde2017populism]. It is emphasized that voters of populist parties do not trust the political system they live in, neither are they satisfied with representative democracy in their country. Populism may be broadly defined as *“a general protest against the checks and balances introduced to prevent ‘the people’s’ direct rule”* [@pelinka2013right]. Summarizing, we can observe the great accordance of scholars, that populist electorate is not supporting the political system and wants to rebel against the established structures.


Indeed, recent events have shown that a large number of citizens are hesitant to encourage European integration. Simultaneously, several parties express euro-criticism and sucessfully mobilize national identity considerations against the European Union [@de2009taking; @hooghe2005calculation; @lubbers2008regarding]. These parties see the EU as a threat to the sovereignty of the nation state. There is an almost allover agreement that right-wing parties generally characterise the EU as unacceptable and should either be reformed or completely abolished [@mudde2007populist]. Yet, the relationship between euro-scepticism and radical right-wing voting behaviour has received little empirical attention in previous studies. @ivarsflaten2005vulnerable showed that euro-scepticism is an important determinant for radical right-wing support in France and Denmark. @van2005some also found a positive relationship between anti-EU sentiments and radical right-wing voting in France. Using data from 2002, @lubbers2007euro focused on the role of euro-scepticism for radical right-wing support in national elections in 13 countries. They found that voting for radical right-wing parties can partly be explained by euro-scepticism, over and beyond other relevant socio-political attitudes. Also, @arzheimer2009christian found evidence for the relevance of euro-scepticism, although he was not able to test its effect next to the major predictor of radical right-wing voting: the unfavourable attitudes towards migrants.




@dassonneville2012electoral:
The disaffected volatile voter Carsten Zelle was not convinced about different theories trying to explain volatility by means of levels of education, political interest or social characteristics. After showing that those theories insufficiently explain volatile behaviour, he develops the ‘frustrated floating voter’-hypothesis. The main argument is that voters behave volatile because of a ‘mood of protest’. According to Zelle, floating voters are: “somewhat less satisfied with the political system, less trusting in parties, and less happy about their favoured party” (Zelle 1995, p. 340). More recently, Dalton and Weldon (2005) investigated the impact of distrust in parties on electoral behaviour. They state “distrust in parties stimulates a marked increase in voter volatility” (Dalton and Weldon 2005, p. 944). Moreover, they also demonstrate that trust in parties is correlated to satisfaction with democracy and the democratic process in general. Peter Söderlund (2008), then, investigated whether volatility is mainly caused by voters’ opinion on a specific party or by “attitudes towards politics in general” (Söderlund 2008, p. 218). His findings point to the first possibility, volatility is significantly related towards how voters perceive the performance of their preferred party. This last approach fits within ‘reward-punishment’-theories developed by rational choice scholars who state that voters judge the performances of parties and vote accordingly (Fiorina, 2002; Key, 1966). While dissatisfaction about parties’ performances is an important reason for changing party preferences or vote choices, it cannot be considered as a fundamental voter characteristic. Rather than such a short-term and fluid attitude, we are interested in the impact of long-term stable politic attitudes on volatility. The longterm stable political attitudes having an impact on volatility mentioned by Zelle (1995) and Dalton and Weldon (2005) –satisfaction with democracy and political trust– are aspects of the ‘political disaffection’- concept. This concept has two aspects, on the one hand there is institutional disaffection, and on the other hand there is political disengagement. Indicators for institutional disaffection are institutional confidence and external political efficacy. Political disengagement can be operationalized by means of political interest, political salience and internal political efficacy (Torcal and Montero, 2006). Political disengagement could be considered as the opposite of political sophistication and is thus taken into account within our analysis. Institutional disaffection, is what Zelle (1995) and Dalton and Weldon (2005) point at and should also be included in an analysis about characteristics of volatile voters. Although, up so far, there is very few work done on the impact of institutional disaffection on volatility, results unambiguously point at its destabilising effect. Consequently we expect voters with low levels of political trust and external political efficacy, variables used to measure institutional disaffection, to be more volatile in their party preferences and vote choices.



### Internal Efficacy

[@buhl06]: 
Since Lazarsfeld et al. (1949), socio-economic status (SES) has played a prominent role in explaining both the decision to vote and participation behaviour. Normally, socio-economic status consists of the individual’s educational level, income, and her occupational status. In theory, a high SES leads to a higher propensity to participate in elections, because individuals with high education levels and/or with a high income have more disposable time and a greater capacity to understand political debates (Kleinhenz 1995). This leads not only to greater political interest, but also to a greater probability of participation. Furthermore, wealthy individuals have an interest in contributing to the stability of the political system by participating in it (Wol nger and Rosenstone 1980).
• Political skills are seen as the most important resource of participation (Bühlmann 2006): individuals with a lot of political interest (Campbell et al. 1976; Lazarsfeld et al. 1949) and internal ef cacy (Campbell et al. 1976) make wider use of all the different possibilities of in uencing politics - including electoral participation - than uninterested individuals or persons who do not think they have the ability to participate in politics.2
• Political attitudes play a crucial role in the decision to vote. Since Campbell et al. (1976), party ties have been considered long-term factors which stabilise electoral choices. However, party ties are also important for participation (Dalton et al. 1984). People with only weak, or no party identi cation at all, show a lower propensity to participate in elections (Pattie and Johnston 1998). An important and widely discussed (especially in German political science (Feist 1992))3 factor is the attitude that voting is a civic duty. If participation in elections is seen as the ful lment of one’s duty as a citizen, the propensity to vote increases.




@valentino2009efficacy:
While most resources such as education, income, and employment status are stable, some psychological forces appear more variable. One such trait is political efficacy: a combination of one’s sense of competence in the political sphere and one’s assessment of the responsiveness of the system (Campbell et al. 1954). A citizen is more likely to participate when she believes her actions can make a difference in politics. This can either be because she considers herself competent and influential—a dimension labeled internal efficacy—or because she is confident that the system is responsive to her and others like her—a dimension labeled external efficacy (Easton 1965; Easton and Dennis 1967; Iyengar 1980). Individuals high in internal efficacy feel they understand how to take part in politics, and are not intimidated by the challenges, conflicts or disagreements that occur in that arena. External efficacy refers to an individual’s belief in the openness and responsiveness of the political system. People high on this dimension believe the system reacts when pressure is applied by citizens, regardless of whether or not they are willing or able to apply that pressure themselves.

@bandura1977self explains behavioral change through performance. A sense of mastery comes with success, and this determines future coping behavior, effort, and persistence in the face of obstacles. When people cope with environmental threats effectively, they gain confidence in their ability to succeed the next time a threat arises. Bandura states, ‘‘People fear and tend to avoid threatening situations they believe exceed their coping skills, whereas they get involved in activities and behave assuredly when they judge themselves capable of handling situations that would otherwise be initiated’’ (p. 194). Applied to politics, we would predict that under threat, citizens who feel confident about their ability to participate should be more likely to act. Participation should then reinforce internal efficacy, especially when it is successful [@bandura1977self].

@kenski2006connections: 
Political efficacy is a determinant of political behavior—without feelings of competency and beliefs that one’s actions are consequential, one has little incentive to participate in politics (Abramson & Aldrich, 1982). Political participation is important because levels of engagement in a democratic system have consequences on the system’s equity (Rosenstone & Hansen, 1993). Theoretically, an optimal democracy would contain citizens who possess high levels of political knowledge, efficacy, and participation [@kenski2006connections].

In The Voter Decides, Campbell, Gurin, and Miller (1954) described the concept of political efficacy as “the feeling that political and social change is possible, and that the individual citizen can play a part in bringing about this change” (p. 187). Several scholars have noted that political efficacy appears to be made of two different constructs, a personal sense of efficacy, commonly known as internal efficacy, and a more system-oriented sense of efficacy, known as external efficacy (Balch, 1974; Converse, 1972; Niemi, Craig, & Mattei, 1991). Niemi et al. explain that internal political efficacy refers “to beliefs about one’s own competence to understand, and to participate effectively in, politics” (p. 1407), whereas external political efficacy refers “to beliefs about the responsiveness of government authorities and institutions to citizen demands” (p. 1408). Although political efficacy is frequently discussed as an overall concept, internal and external efficacy items typically fall into two unique dimensions, and these dimensions interact differently with other political variables (Balch, 1974)


Research in several European countries has shown that voters for the radical
right-wing parties feel less politically efficacious, more alienated, and more dissatisfied with the established parties, the political institutions, and the demo..
cratic system in general (Beta 1994:35..67).

### Economic Deprivation

text: what unites right wing populists in western europe
All existing theories of party system evolution, be they inspired by the Downsean economic tradition (Downs, 1957) or by the political sociology tradition of Lipset and Rokkan (1967), agree on one point. They implicitly or explicitly argue that unless there is some sort of societal change that gives rise to a widespread public grievance, a major change in the party system is unlikely to occur.3 Thus, in the most detailed explanation yet of the pattern of party systems evolution in Western Europe, Lipset and Rokkan emphasized the intimate connections between grievances, the expansion of suffrage, and the rise of new parties. 


#### The Protest Vote

This approach builds on a widely accepted idea that radical right-wing parties gain from political protest. From this point of view, voters for these parties are not attracted by their anti-immigrant stances, but express predominantly political dissatisfaction [@mudde2007populist]. Although several studies emphasize that voters not only cast a radical right-wing vote based on political dissatisfaction, the protest proposition explains at least some of the variation in radical right-wing voting [@ivarsflaten2005vulnerable]. We expect people who perceive their socio-economic situation as deprived to oppose established parties. They will be dissatisfied politically, feel more powerless, and are consequently more likely to cast a radical right-wing vote, since parties on the radical right claim to listen to the dissatisfied and oppose government decisions. People who perceive deprivation in their present socio-economic situation are more likely to vote for a radical right-wing party, as they are more dissatisfied politically [@werts2013euro].

#### Ethnic competition theory

Contributors to the ethnic competition theory proposed that ethnic groups sharing similar economic interests are in competition for scarce resources, which induces perceived ethnic threat and intergroup antagonistic attitudes (Coser, 1956; Levine and Campbell, 1972). In most European countries, ethnic out-groups (search for) work particularly in the lowest labour segments, where unemployment levels tend to be higher (Kiehl and Werner, 1999). Social categories that hold similar positions to ethnic minorities perceive more ethnic threat and therefore have stronger exclu- sionary reactions, e.g. voting for radical right-wing parties (Lubbers et al., 2002).

Coffe (2005) and Van der Brug and Fennema (2003) stressed the relevance of more general threat perceptions: deterioration of the living environment will also nourish feelings of threat, particularly among lower social strata that are more likely to live in neighbourhoods with relatively high levels of criminality. Therefore, those people are expected to feel unsafe in their own neighbourhood more often (e.g. Hale, 1996). Moreover, people may feel directly threatened by ethnic minorities, since ethnic groups are overrepresented in criminality statistics (Dagevos and Gijsberts, 2010). Since radical right-wing parties claim to serve the interests of the in-group and suggest that foreigners are related to a variety of problems, these parties may be an attractive option for people from lower social strata.
H1: Lower-educated people, manual workers and unemployed people are more likely to vote for a radical right-wing party, (a) as they experience more ethnic threat, and (b) as their level of subjective victimization is generally higher.


Earlier research results were consistent with the hypothesis that antiimmigration
attitudes are an important factor for predicting who will vote for
radical right-wing populist parties (e.g., Lubbers & Scheepers 2000; Lubbers
et al. 2002; Norris 2005). Even if not all voters who are sceptical of immigration
vote for radical right-wing parties, most voters who do vote for those parties
have such attitudes

#### Theory of psychological interests

The classic study of the Authoritarian Personality (Adorno et al., 1950) gives another explanation of why lower social strata would be more likely to vote for radical right-wing parties (e.g. Lipset, 1981 [1960]; Falter and Klein, 1994). Its core idea is that the socio-economic position of lower social strata may be characterized by poverty and deprivation, which in turn would create anxiety and frustration. To deal with anxiety and frustration, these particular strata are likely to submit them- selves to strong authorities or strong traditional norms (Scheepers et al., 1990). Radical right-wing parties serve these psychological needs, as these parties empha- size traditional norms and a strong leader (Lubbers et al., 2002).
H2: Lower-educated people, manual workers, unemployed people, as well as people who perceive deprivation in their present socio-economic situation, are more likely to vote for a radical right-wing party, as they favour authoritarian attitudes.



In addition, we control for age, sex, and confession. With regard to life- cycle effects, it is assumed that younger individuals are more likely to abstain from voting (Kleinhenz 1995). Gender differences, in turn, are seen as both consequences of generation effects and of structural differences (Ballmer-Cao and Sgier 1998). Lastly, in the Swiss case, confession is an important determinant of electoral participation (Wernli 2001).



## Contextual Factors
Various approaches can be found in internationally comparative participation research which seek to explain the differing participation levels in democratic parliamentary elections. Clearly, three research directions – the politico- institutional perspective, the politico-cultural approach, and the theory of socio- economic resources – dominate the debate, while in research so far, institutional in uencing variables have proven particularly operative and signi cant (Franklin 2004; Jackman and Miller 1995; Lijphart 1997: 7; Norris 2004). In this section, we sum up the essential theoretical standpoints of these research perspectives.4


### Institutional Perspective
In existing comparative electoral participation research, the most attention by far is paid to politico-institutional determinants (Lijphart 1997: 7). Following the tradition of neo-institutionalism, this approach conceives of institutions as ‘rules of the game’ which facilitate certain action alternatives while preventing others. In other words: institutions, in this view, function equally as formalised rules and as social norms which facilitate, limit, or stimulate individual attitudes and actions (Immergut 1998; Mayntz and Scharpf 1995: 43). Macro-quantitative research generally distinguishes between politico-institutional conditions in the broader sense and factors concerning electoral law and administration (Norris 2004: 153). While characteristics of the electoral, party, and government system belong to the former set of conditions, primarily organisational stipulations such
as the existence of compulsory voting belong to the second category. Advocates of this institutional research perspective generally look for incentives or possible institutionalised barriers which coincide with participation in an election (Blais and Dobrzynska 1998; Jackman and Miller 1995: 469; Norris 2004).

Pursuant to the Swiss constitution (Article 149.2), the electoral system is the same in all cantons, i.e. proportional representation (PR) is used throughout all of the cantons. However, the number of available seats varies greatly from canton to canton and corresponds to the size of the population: while in the largest canton, Zurich, 34 seats are allocated, the candidates in the six smallest cantons compete for only one seat. In practice, this situation comes close to a majority vote. Relevant research identi es the type of electoral system as the  rst relevant variable towards an explanation of differences in electoral participation levels (Siaroff and Merer 2002). Majority electoral systems are seen as barriers to high electoral participation, since (it is argued) elections are not controversial in safe constituencies or strongholds, and supporters of the previously defeated party or small parties stay away from the election because they consider their vote to be ineffective (Ladner and Milner 1999). Additionally, previously defeated parties reduce their mobilisation efforts. In contrast, turnout should be higher under proportional systems, since voters will not feel that their vote is wasted, more parties are likely to run, and parties will have an incentive to campaign everywhere (Siaroff and Merer 2002: 920). In Switzerland, single-seated cantons resemble majority systems. Again, in cantons with proportional systems the number of parties increases with the number of available seats (Wernli 2001). Against this background we hypothesise that an increasing number of seats leads to a higher propensity to vote.

Party system. In their search for the driving forces behind participation rates, researchers frequently refer to the competitive situation within the party system (Blais and Dobrzynska 1998: 249; Wernli 1998). This approach assumes that whilst elections with pre-determined outcomes bring about a degree of apathy and ignorance amongst voters, a strongly competitive inter-party situation at the outset has a stimulating effect.5 At the same time, the weight of each individual vote is argued to increase with the supposed marginality of an electoral outcome. In other words: the more consequences an individual vote has for an electoral result, it is argued, the more likely citizens are to go to the ballot (Freitag 2005). Furthermore, the number of parties is assumed to have an effect on electoral participation. The more fragmented a party system, the more multi-faceted the party-ideological spectrum becomes, and thus the more possibilities the voter has to  nd candidates in which he sees his interests represented and realised (Blais and Dobrzynska 1998: 248). Thus, a large party diversity is said to boost willingness to participate in political elections. Finally, a high level of electoral participation should be traceable to a polarised party system, since opposite party camps are adept at keeping their respective clientele particularly close (Crepaz 1990; Norris 2004: 167).
Institutions. Two competing assessments can be formulated regarding the in uence of direct democracy on participation at parliamentary elections. The  rst conjecture assumes that a culture of active referendum democracy stimulates citizens’ political interest (Hajnal and Lewis 2003). Wernli (1998), for instance, comparing 10 Swiss cantons concludes, that electoral participation is higher in the cantons where a more intensive form of direct democracy is practised The opposite to this hypothesis is the assumption of a negative relationship between direct democracy and electoral democracy. At least two reasons speak for this claim:  rst, sundry popular initiatives and referenda restrict the competencies of government, parliament, and parties. The voter recognises that she is in a position to decide authoritatively on important issues, independently and without recourse to members of parliament. Thus, from this perspective, political questions are decided on primarily in referenda and not at (less relevant) elections (Bühlmann et al. 2003; Linder 1999: 315). Second, where there are several pillars of political co-determination, it is conceivable that a certain fatigue could arise regarding elections and referenda, mainly at the expense of less signi cant ballots (Jackman and Miller 1995: 483) and above all in cantons where the use of direct democracy instruments is high. Furthermore, cantons with a well-developed communal autonomy could be expected to ascribe little importance to national authorities, since the latters’ limited powers of action and decision mean that elections to national parliament are considered largely irrelevant.
Electoral law and administration. Among the factors concerning electoral law and administration, compulsory voting is particularly signi cant in the explanation of electoral participation (Lijphart 1997). On the international level, Italy and the Netherlands pursued this arrangement until 1993 and 1970 respectively. Today, compulsory voting continues to exist, for instance, in Australia, Belgium, Brazil, Bulgaria, Costa Rica, Greece, Luxemburg, Lichtenstein, Mexico, Peru, Singapore, Turkey, and Cyprus. Among the Swiss cantons, compulsory voting exists only in the canton of Schaffhausen. Here, as in Australia or Belgium, citizens can be driven to vote by the threat of retrospective penalties.6 While regular participation in the democratic process leads to the acquirement of a certain political competence and to the development of an active citizen’s political interest (Pateman 1970; Wernli 1998), compulsory voting leads us to expect a higher rate of participation at ballots (Franklin 2004).

### Cultural Determinants
Exponents of the politico-cultural and socio-integrative perspective emphasise that the willingness to participate in elections is not so much a result of institutional incentives and stimulants, as, primarily, an acquired habit (Norris 2004: 154). Accordingly, other investigations attribute an in uence on the level of electoral participation to socio-political and politico-cultural factors (Crepaz 1990; Gray and Caul 2000; Siaroff and Merer 2002).

*Socio-political integration characteristics.* At least since Tocqueville‘s (1994) analyses, social science has been dealing with the signi cance of clubs and organisations for the social and political integration of individualistic societies. This perspective’s fundamental ideas can be traced back to the politico-cultural research of the 1960s, when voluntary organisations are considered to be “the most important foundations” of stable democracies, and were thought to secure the latter’s continued existence (Almond and Verba 1965: 220ff.). Here, organisations act not only as mediums of political socialisation, but also as “schools for democracy”, since they enable the “membership role” to be combined with the “role of citizen” in social practice. We expect cantons with a high density of membership, particularly in trade unions and parties, but also in other formal associations, to display a higher level of participation. A high cantonal degree of involvement in this respect is regarded as an environment which fosters civic behaviour, including the willingness to support the political system through electoral participation.

*Politico-cultural characteristics.* In the Swiss context, Catholicism is traditionally considered a signi cant, historically established politico-cultural driving force behind electoral participation. According to Wernli (1998: 96ff.), there is a particularly strong bond in the Swiss cantons between the Christian Democratic Party (CVP) and Catholics. This historically entrenched relationship dates back to the defeat of the Catholic coalition at the end of the Sonderbundkrieg (short Swiss civil war, 1847). In the aftermath of this war, the Catholic population grew to perceive itself as a minority subordinated to worldly and modernising forces, and withdrew into a kind of isolated society in the strongholds of the Catholic cantons (Linder 1999: 37; Geser 2004). In these cantons, federal order guaranteed the continuation of Catholic morals and customs. It is thought that in cantons with a Catholic majority, elections are perceived of as regular challenges to the bastion of Catholicism and essential Christian religious values. This perception, together with the clientelistic entanglements between party and ideology, is suggested to act as a mobilising force on electoral participation. In view of the enduring confessional-political culture in Switzerland (cf. Geser 2004), these connections ought also to affect more recent developments and to render political Catholicism a propulsive force on political participation.
At least two reasons oblige us to take not only the confessional, but also the language, cleavage into consideration. First, we can distinguish between the cantons by their type of democratic system. In existing research, the non- German cantons have typically been seen as representative systems, while the German speaking cantons pass as more direct-democratic systems (Kriesi 1998; Wernli 2001): not only are cantonal constitutions in the Latin areas more oriented towards representative democracy, with fewer opportunities of direct legislation (Ladner 1991), but the direct democratic instruments also are used more seldom than in the German speaking cantons (Linder 1999). Second, the non-German cantons have minority status at the national level. We therefore suggest that individuals living in these cantons concentrate more on cantonal than federal politics, and thus tend to exercise their national voting rights less intensively. The  rst point of view leads us to expect that a higher degree of importance will be attached to elections, and that there will thus be a higher electoral turnout in Latin cantons. The second point, however, leads to contrary assumptions.


### Socio-economic Factors
Besides the approaches mentioned so far, extant comparative investigations refer to the effect of socio-economic and socio-demographic factors on participation rates at political elections. Thus, for instance, economic strength and population size are mentioned as particularly relevant in uencing variables (Blais and Dobrzynska 1998: 241ff.; Norris 2004; Siaroff and Merer 2002: 917).
*Economic strength and modernity.* Where existing research draws upon societies’ cognitive and material resources to explain varying electoral participation rates, it refers primarily to differing levels of modernity and economic strength. A well- functioning economic system causes positive attitudes to develop towards the political system, strengthens political interest, and bestows the feeling that one’s potential participation will be politically effective (Verba and Nie 1972: 125ff.). Additionally, the higher a democracy’s level of socio-economic development or degree of modernity, the higher will be the rate of electoral participation (Blais and Dobrzynska 1998: 241ff.; Siaroff and Merer 2002). With a view to population size, researchers assume that less densely populated areas will display lower electoral participation, since a scattered population is more dif cult to mobilise and relevant information is less accessible (Blais and Dobrzynska 1998: 242ff.).



