---
output: pdf_document
---

add: conclusion: future work:
Trust in the political establishment and cofidence in the responsiveness of the political system are often treated intuitively as synonyms. Consequently, external efficacy is mostly analysed with framework of political trust. -> future work should differentiate trust and efficacy methodisch....besseren einblick in die mechanismen...


Our empirical findings are mainly alongside with our hypotheses. Therefore we can confirm that low levels of political trust leads to a higher likelihood to vote for a right-wing party. We could show that distrust in the European institutions partly loads on a unique dimension which was reason enough to separately include the term in the final regression model. While the extracted principal component of the trust items turn out to be unstable, the eurosceptic term always remains negatively. Another major explanatory are anti-immigration attitudes. Through PCA we extracted the first two dimensions loading on a cultural and economic dimension. The parameters suggested that economic deprivation as well as fear of cultural backslash contribute both independently to an increases likelihood to vote for a right-wing party. People with higher income as well as women are less likely attracted by right populists.

On macro level we found evidence of an increased likelihood for people living in countries with a high percentage of refugees. This effect shrinks for countries with either extreme homogeneous or heterogeneous ethnic populations. Furthermore economic and social progress measured by HDI reduces the likelihood for citizens to vote for a radical right-wing party. The effect of direct democratic institutions could not be confirmed. 

This analysis is highly method driven and therefore offers several points for further improvements. First, more experimentation is needed to identify the right amount of populist indicators to improve the quality of the cluster labels. Second, Bayesian Logistic Regression could be used to better understand model uncertainty and to replace p-values with posterior distributions of each parameter. And finally, panel data on these  issues would provide further inside into the causal mechanisms at stake. 

